templates:
  deluge_basic:
    verify_ssl_certificates: no
    free_space:
      path: /media/Storage
      # in MB so this is 5GB
      space: 5000
    deluge:
      path: /media/Storage/Torrents/Pool/
      host: localhost
      port: 58846
      username: deluge
      password: deluge

email:
  from: vink@mail.brak
  to: paul@mail.brak
  subject: Downloads
  smtp_host: localhost

tasks:
  LAS:
    priority: 2
    rss: http://www.jupiterbroadcasting.com/feeds/lasstorrent.xml
    #download: /media/Storage/Torrents
    series:
      - LAS
    accept_all: yes
    limit_new: 1
    template:
      - deluge_basic
    deluge:
      movedone: /media/Storage/Television/LAS/
      label: LAS
  Tech:
    priority: 3
    rss: http://bitlove.org/jupiterbroadcasting/techsnap60/feed
    #download: /media/Storage/Torrents/
    series:
      - Tech Snap
    accept_all: yes
    limit_new: 1
    template:
      - deluge_basic
    deluge:
      movedone: /media/Storage/Television/Tech Snap/
      label: TechSnap
    regexp:
      reject:
        - "Jupiter."
      from: filename

## Working on a Task to get F1 Races, DirecTV package no longer provides NBC Sports
  F1:
    priority: 7
    #download: /media/Storage/Torrents/
    template:
      - deluge_basic
    deluge:
      label: F1
      movedone: /media/Storage/Television/Formula 1
    #quality: 720p+
    regexp:
      reject_excluding:
        #- "2013"
        #- "Sky"
        - ".SkyF1HD"
        #- ".2013"
        # this will be tough, I prefer the SkyTV broacast, but must fallback to BBC if it is not available, but if i don't filter at all, I get multiple broadcasts of the race
    discover:
      what:
        - mock:
          - {title: Formula 1}
      from:
        - piratebay: yes

## Automatic TV Shows
  Paul:
    priority: 1
    #download: /media/Storage/Torrents/
    template:
      - deluge_basic
    deluge:
      main_file_only: yes
      label: FlexgetTV
    content_filter:
      reject:
        - '*.rar'
    configure_series:
      settings:
        target: 720p+
        timeframe: 4 days
        propers: no
        upgrade: yes
        set:
          movedone: /media/Storage/Television/{{series_name}}/Season {{series_season}}/
          content_filename: "{{series_name}} - {{series_id}}"
      from:
        csv:
          url: 'file:///home/vink/.flexget/shows.csv'
          values:
            title: 1
            url: 1    
    discover:
      what:
        - csv:
            url: 'file:///home/vink/.flexget/shows.csv'
            values:
              title: 1
              url: 1
      from:
        - piratebay: yes
        - torrentz: any
        - isohunt: all
        #- search_rss: http://extratorrent.com/rss.xml?type=search&search={{search_term|replace(' ', '+')}}
  
  moviesHigh:
    priority: 5
    template:
      - deluge_basic
    deluge:
      main_file_only: yes
      label: Movie
      movedone: /media/Auxillary/Film/
    content_filter:
      reject:
        - '*.rar'
    limit_new: 1
    imdb_lookup: no
    tmdb_lookup: no
    imdb:
      accept_languages:
        - english
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - piratebay: yes
        - torrentz: any
        #- search_rss: http://extratorrent.com/rss.xml?type=search&search={{search_term|replace(' ', '+')}}
    movie_queue: accept
    torrent_alive: 4
    quality: 1080p
    exec:
      on_output:
        for_accepted: sed /'{{imdb_name}}'/d -i /home/vink/.flexget/movies.csv
  
  moviesMid:
    priority: 6
    template:
      - deluge_basic
    deluge:
      main_file_only: yes
      label: Movie
      movedone: /media/Auxillary/Film/
    content_filter:
      reject:
        - '*.rar'
    limit_new: 1
    imdb_lookup: no
    tmdb_lookup: no
    imdb:
      accept_languages:
        - english
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - piratebay: yes
        - torrentz: any
    movie_queue: accept
    torrent_alive: 4
    quality: 720p
    exec:
      on_output:
        for_accepted: sed '/{{imdb_name}}'/d -i /home/vink/.flexget/movies.csv

  queueMovies:
    priority: 4
    csv:
      url: 'file:///home/vink/.flexget/movies.csv'
      values:
        title: 1
        url: 1
    accept_all: yes
    movie_queue: add
